//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomamaaApp.Properties
{
    using System;

    /// <summary>
    /// Strongly-typed resource class for localized strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        public Resources() { }

        /// <summary>
        /// Cached ResourceManager instance
        /// </summary>
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoomamaaApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the CurrentUICulture for resource lookups
        /// </summary>
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string AddAgeLabel => ResourceManager.GetString("AddAgeLabel", resourceCulture);
        public static string AddAnimalButton => ResourceManager.GetString("AddAnimalButton", resourceCulture);
        public static string AddAnimalHeader => ResourceManager.GetString("AddAnimalHeader", resourceCulture);
        public static string AddAnimalWindowTitle => ResourceManager.GetString("AddAnimalWindowTitle", resourceCulture);
        public static string AddButton => ResourceManager.GetString("AddButton", resourceCulture);
        public static string AddNameLabel => ResourceManager.GetString("AddNameLabel", resourceCulture);
        public static string AddTypeLabel => ResourceManager.GetString("AddTypeLabel", resourceCulture);
        public static string AgeLabel => ResourceManager.GetString("AgeLabel", resourceCulture);
        public static string AgeRangeError => ResourceManager.GetString("AgeRangeError", resourceCulture);
        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture);
        public static string Bear_ActCrazy => ResourceManager.GetString("Bear_ActCrazy", resourceCulture);
        public static string Bear_Sound => ResourceManager.GetString("Bear_Sound", resourceCulture);
        public static string Cat_ActCrazy => ResourceManager.GetString("Cat_ActCrazy", resourceCulture);
        public static string Cat_Sound => ResourceManager.GetString("Cat_Sound", resourceCulture);
        public static string Combo_Bear => ResourceManager.GetString("Combo_Bear", resourceCulture);
        public static string Combo_Cat => ResourceManager.GetString("Combo_Cat", resourceCulture);
        public static string Combo_Dog => ResourceManager.GetString("Combo_Dog", resourceCulture);
        public static string Combo_Duck => ResourceManager.GetString("Combo_Duck", resourceCulture);
        public static string Combo_Horse => ResourceManager.GetString("Combo_Horse", resourceCulture);
        public static string Combo_Monkey => ResourceManager.GetString("Combo_Monkey", resourceCulture);
        public static string Combo_Pig => ResourceManager.GetString("Combo_Pig", resourceCulture);
        public static string Combo_Sheep => ResourceManager.GetString("Combo_Sheep", resourceCulture);
        public static string CrazyActionButton => ResourceManager.GetString("CrazyActionButton", resourceCulture);
        public static string Dog_ActCrazy => ResourceManager.GetString("Dog_ActCrazy", resourceCulture);
        public static string Dog_Sound => ResourceManager.GetString("Dog_Sound", resourceCulture);
        public static string Duck_ActCrazy => ResourceManager.GetString("Duck_ActCrazy", resourceCulture);
        public static string Duck_Sound => ResourceManager.GetString("Duck_Sound", resourceCulture);
        public static string ErrorTitle => ResourceManager.GetString("ErrorTitle", resourceCulture);
        public static string FeedButton => ResourceManager.GetString("FeedButton", resourceCulture);
        public static string FoodLabel => ResourceManager.GetString("FoodLabel", resourceCulture);
        public static string Horse_ActCrazy => ResourceManager.GetString("Horse_ActCrazy", resourceCulture);
        public static string Horse_Sound => ResourceManager.GetString("Horse_Sound", resourceCulture);
        public static string InputErrorTitle => ResourceManager.GetString("InputErrorTitle", resourceCulture);
        public static string LogAteFormat => ResourceManager.GetString("LogAteFormat", resourceCulture);
        public static string LogSaidFormat => ResourceManager.GetString("LogSaidFormat", resourceCulture);
        public static string MakeSoundButton => ResourceManager.GetString("MakeSoundButton", resourceCulture);
        public static string Monkey_ActCrazy => ResourceManager.GetString("Monkey_ActCrazy", resourceCulture);
        public static string Monkey_Sound => ResourceManager.GetString("Monkey_Sound", resourceCulture);
        public static string NameLabel => ResourceManager.GetString("NameLabel", resourceCulture);
        public static string NoCrazyActionFormat => ResourceManager.GetString("NoCrazyActionFormat", resourceCulture);
        public static string Pig_ActCrazy => ResourceManager.GetString("Pig_ActCrazy", resourceCulture);
        public static string Pig_Sound => ResourceManager.GetString("Pig_Sound", resourceCulture);
        public static string PleaseEnterValidName => ResourceManager.GetString("PleaseEnterValidName", resourceCulture);
        public static string PleaseEnterValidNumberAge => ResourceManager.GetString("PleaseEnterValidNumberAge", resourceCulture);
        public static string PleaseSelectAnimalType => ResourceManager.GetString("PleaseSelectAnimalType", resourceCulture);
        public static string RemoveAnimalButton => ResourceManager.GetString("RemoveAnimalButton", resourceCulture);
        public static string Sheep_ActCrazy => ResourceManager.GetString("Sheep_ActCrazy", resourceCulture);
        public static string Sheep_Sound => ResourceManager.GetString("Sheep_Sound", resourceCulture);
        public static string UnknownAnimalType => ResourceManager.GetString("UnknownAnimalType", resourceCulture);
    }
}
